resolver: nightly-2018-11-07

# due to functor-infix
allow-newer: true

packages:
  - 'grin'

extra-deps:
  - monad-gen-0.3.0.1
  - functor-infix-0.0.5
  - QuickCheck-GenT-0.2.0
  - megaparsec-6.5.0
  - neat-interpolation-0.3.2.2
  - set-extra-1.4.1
  - llvm-hs-pretty-0.6.1.0

flags:
  llvm-hs:
    shared-llvm: true

build:
  test-arguments:
    additional-args:
      - "--seed=11010"
